"""Generate agent.md (Claude Code subagent markdown) for every pilot.

Reads backend/agents/<pilot>/manifest.py for id/title/description,
then reads SOUL.md + skill/SKILL.md to build the body.
Writes backend/agents/<pilot>/agent.md.

Idempotent — overwrites existing agent.md each run so edits to
SOUL.md / manifest.py propagate. Do NOT edit agent.md directly;
edit the source files and re-run.
"""
from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

PILOTS = [
    "auditpilot", "autopilot", "gbppilot", "pilotcore", "projectpilot",
    "qapilot", "redditpilot", "reportpilot", "strategypilot", "websitepilot",
]

MODELS = {
    "auditpilot": "opus", "autopilot": "opus", "gbppilot": "sonnet",
    "pilotcore": "opus", "projectpilot": "sonnet", "qapilot": "sonnet",
    "redditpilot": "sonnet", "reportpilot": "sonnet",
    "strategypilot": "opus", "websitepilot": "sonnet",
}


def load_manifest(pilot_dir: Path) -> dict:
    """Import manifest.py without importing its parent package."""
    manifest_path = pilot_dir / "manifest.py"
    spec = importlib.util.spec_from_file_location(
        f"manifest_{pilot_dir.name}", manifest_path
    )
    module = importlib.util.module_from_spec(spec)
    backend_dir = pilot_dir.parents[1]
    sys.path.insert(0, str(backend_dir))
    try:
        spec.loader.exec_module(module)
    finally:
        sys.path.pop(0)
    m = module.manifest
    return {
        "id": m.id, "title": m.title, "description": m.description,
        "version": m.version, "icon": m.icon, "category": m.category,
        "tags": list(m.tags),
    }


def extract_when_to_trigger(skill_md: str) -> str:
    """Pull a '## When …' section from SKILL.md (best-effort)."""
    match = re.search(
        r"^## When [^\n]*\n(.*?)(?=\n## |\Z)",
        skill_md, re.DOTALL | re.MULTILINE,
    )
    return match.group(1).strip() if match else ""


def extract_route_prefix(manifest_src: str) -> str:
    match = re.search(r'route_prefix="([^"]+)"', manifest_src)
    return match.group(1) if match else ""


def yaml_quote(value: str) -> str:
    """Wrap a string for safe YAML frontmatter output.

    Escapes internal backslashes and double quotes, then double-quotes.
    Safe against values containing ': ' which would otherwise break
    unquoted YAML scalars.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def build_agent_md(pilot: str, pilot_dir: Path) -> str:
    manifest = load_manifest(pilot_dir)
    skill_path = pilot_dir / "skill" / "SKILL.md"
    skill_md = skill_path.read_text() if skill_path.exists() else ""

    triggers = extract_when_to_trigger(skill_md)
    model = MODELS.get(pilot, "sonnet")

    description = manifest["description"].replace("\n", " ").strip()
    if len(description) > 200:
        description = description[:197] + "..."

    route_prefix = extract_route_prefix((pilot_dir / "manifest.py").read_text())

    frontmatter = (
        "---\n"
        f"name: proofpilot-{pilot}\n"
        f"description: {yaml_quote(description)}\n"
        f"model: {model}\n"
        "---\n\n"
    )

    body = (
        f"# {manifest['title']}\n\n"
        f"{manifest['icon']} **Category:** {manifest['category']} · "
        f"**Version:** {manifest['version']} · "
        f"**Tags:** {', '.join(manifest['tags'])}\n\n"
        f"## Identity\n\n"
        f"See [SOUL.md](./SOUL.md) for full voice + values.\n\n"
    )

    if triggers:
        body += f"## When to use\n\n{triggers}\n\n"
    else:
        # Fallback: derive from manifest description so the section is never empty.
        body += (
            "## When to use\n\n"
            f"Use when the task matches this pilot's purpose: "
            f"{manifest['description'].replace(chr(10), ' ').strip()}\n\n"
        )

    body += (
        "## How it runs\n\n"
        f"Backend: `POST {route_prefix}`. "
        "See [CLAUDE.md](./CLAUDE.md) for orchestration + stages, "
        "[TOOLS.md](./TOOLS.md) for integrations, "
        "[skill/SKILL.md](./skill/SKILL.md) for the full playbook.\n\n"
        "## Source of truth\n\n"
        f"`backend/agents/{pilot}/` in `get-proofpilot/proofpilot-agent-hub`. "
        f"The skill at `~/.claude/skills/proofpilot-{pilot}/` loads automatically "
        "when this agent runs. To update behavior, edit the source files and "
        "`git pull` on each laptop.\n\n"
        "_This file is generated by `scripts/generate_pilot_agents.py`. "
        "Do not edit directly — edit SOUL.md, manifest.py, or skill/SKILL.md._\n"
    )

    return frontmatter + body


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    pilots_dir = repo_root / "backend" / "agents"

    for pilot in PILOTS:
        pilot_dir = pilots_dir / pilot
        if not pilot_dir.is_dir():
            print(f"SKIP {pilot}: directory missing")
            continue
        agent_md_path = pilot_dir / "agent.md"
        content = build_agent_md(pilot, pilot_dir)
        agent_md_path.write_text(content)
        print(f"wrote: {agent_md_path.relative_to(repo_root)}")


if __name__ == "__main__":
    main()
